# Generated by Django 4.0.3 on 2022-03-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soufian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='career',
            field=models.CharField(max_length=50),
        ),
    ]
